[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 16:35:32,444 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@27bc4ec8] to prepare test instance [sk.qbsw.code.security.test.CJasyptTestCase@3bd840d9]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:308)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [spring/test-db.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [com.microsoft.sqlserver.jdbc.SQLServerDriver]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1361)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:84)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:280)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:304)
	... 24 more
Caused by: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [com.microsoft.sqlserver.jdbc.SQLServerDriver]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:102)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1358)
	... 38 more
[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 16:35:32,620 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@27bc4ec8] to prepare test instance [sk.qbsw.code.security.test.CJasyptTestCase@482d59a3]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:308)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [spring/test-db.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [com.microsoft.sqlserver.jdbc.SQLServerDriver]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1361)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:84)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:280)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:304)
	... 24 more
Caused by: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [com.microsoft.sqlserver.jdbc.SQLServerDriver]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:102)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1358)
	... 38 more
[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 16:40:06,413 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@43a3aa2c] to prepare test instance [sk.qbsw.code.security.test.CJasyptTestCase@2df95165]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:308)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/test-db.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No persistence unit with name 'persistenceContext' found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:563)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:84)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:280)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:304)
	... 24 more
Caused by: java.lang.IllegalArgumentException: No persistence unit with name 'persistenceContext' found
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.obtainPersistenceUnitInfo(DefaultPersistenceUnitManager.java:393)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.determinePersistenceUnitInfo(LocalContainerEntityManagerFactoryBean.java:244)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:196)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
	... 37 more
[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 16:40:06,595 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@43a3aa2c] to prepare test instance [sk.qbsw.code.security.test.CJasyptTestCase@3e9c22ff]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:308)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/test-db.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No persistence unit with name 'persistenceContext' found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:563)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:84)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:280)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:304)
	... 24 more
Caused by: java.lang.IllegalArgumentException: No persistence unit with name 'persistenceContext' found
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.obtainPersistenceUnitInfo(DefaultPersistenceUnitManager.java:393)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.determinePersistenceUnitInfo(LocalContainerEntityManagerFactoryBean.java:244)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:196)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
	... 37 more
[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 16:52:15,566 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@1e34f445] to prepare test instance [sk.qbsw.code.security.test.CJasyptTestCase@2690ed81]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:308)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/test-db.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: persistenceContext] Unable to build EntityManagerFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:563)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:84)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:280)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:304)
	... 24 more
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: persistenceContext] Unable to build EntityManagerFactory
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
	at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:74)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:225)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
	... 37 more
Caused by: org.hibernate.HibernateException: Dialect class not found: sk.qbsw.hibernate.orm.dialect.SQLServer2012Dialect
	at org.hibernate.dialect.resolver.DialectFactory.constructDialect(DialectFactory.java:159)
	at org.hibernate.dialect.resolver.DialectFactory.buildDialect(DialectFactory.java:99)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:117)
	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2863)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2859)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1870)
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:906)
	... 42 more
Caused by: java.lang.ClassNotFoundException: sk.qbsw.hibernate.orm.dialect.SQLServer2012Dialect
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:171)
	at org.hibernate.util.ReflectHelper.classForName(ReflectHelper.java:192)
	at org.hibernate.dialect.resolver.DialectFactory.constructDialect(DialectFactory.java:156)
	... 48 more
[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 16:52:15,804 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@1e34f445] to prepare test instance [sk.qbsw.code.security.test.CJasyptTestCase@66f4652]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:308)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/test-db.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: persistenceContext] Unable to build EntityManagerFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:563)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:84)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:280)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:304)
	... 24 more
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: persistenceContext] Unable to build EntityManagerFactory
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
	at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:74)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:225)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
	... 37 more
Caused by: org.hibernate.HibernateException: Dialect class not found: sk.qbsw.hibernate.orm.dialect.SQLServer2012Dialect
	at org.hibernate.dialect.resolver.DialectFactory.constructDialect(DialectFactory.java:159)
	at org.hibernate.dialect.resolver.DialectFactory.buildDialect(DialectFactory.java:99)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:117)
	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2863)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2859)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1870)
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:906)
	... 42 more
Caused by: java.lang.ClassNotFoundException: sk.qbsw.hibernate.orm.dialect.SQLServer2012Dialect
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:171)
	at org.hibernate.util.ReflectHelper.classForName(ReflectHelper.java:192)
	at org.hibernate.dialect.resolver.DialectFactory.constructDialect(DialectFactory.java:156)
	... 48 more
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,940 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,942 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,945 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,945 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,948 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,948 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,951 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,952 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,955 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 16:53:21,956 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,923 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,925 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,928 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,928 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,931 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,931 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,934 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,935 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,937 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:12,938 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 17:04:13,097 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@3b9fa8f7] to prepare test instance [sk.qbsw.code.security.test.CAuthenticationTestCase@6f0e0eb5]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sk.qbsw.code.security.test.CAuthenticationTestCase': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private sk.qbsw.core.security.service.IAuthorizationService sk.qbsw.code.security.test.CAuthenticationTestCase.authorizationService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No matching bean of type [sk.qbsw.core.security.service.IAuthorizationService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1074)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:374)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:110)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private sk.qbsw.core.security.service.IAuthorizationService sk.qbsw.code.security.test.CAuthenticationTestCase.authorizationService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No matching bean of type [sk.qbsw.core.security.service.IAuthorizationService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:502)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:84)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:282)
	... 26 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No matching bean of type [sk.qbsw.core.security.service.IAuthorizationService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:920)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:789)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:703)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:474)
	... 28 more
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,595 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,597 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,602 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,602 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,604 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,605 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,607 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,608 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,610 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:04:59,610 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
[org.springframework.test.context.TestContextManager # ERROR # 02.01.2014 17:04:59,770 # main # TestContextManager.java # org.springframework.test.context.TestContextManager:prepareTestInstance:324 ] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@71d0e17a] to prepare test instance [sk.qbsw.code.security.test.CAuthenticationTestCase@48834af6]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sk.qbsw.code.security.test.CAuthenticationTestCase': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private sk.qbsw.core.security.service.IAuthenticationService sk.qbsw.code.security.test.CAuthenticationTestCase.authenticationService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [sk.qbsw.core.security.service.IAuthenticationService] is defined: expected single matching bean but found 2: [cLoginService, ldapAuthenticationService]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1074)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:374)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:110)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:220)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:301)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:303)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private sk.qbsw.core.security.service.IAuthenticationService sk.qbsw.code.security.test.CAuthenticationTestCase.authenticationService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [sk.qbsw.core.security.service.IAuthenticationService] is defined: expected single matching bean but found 2: [cLoginService, ldapAuthenticationService]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:502)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:84)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:282)
	... 26 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [sk.qbsw.core.security.service.IAuthenticationService] is defined: expected single matching bean but found 2: [cLoginService, ldapAuthenticationService]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:796)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:703)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:474)
	... 28 more
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,335 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,338 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,341 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,341 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,344 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,344 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,347 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,347 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,350 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:07:15,350 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,024 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,026 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,029 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,030 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,032 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,032 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,035 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,035 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,038 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:30,038 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,337 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,339 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,343 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,343 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,346 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,346 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,351 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,351 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,354 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:08:48,355 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,898 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,900 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,903 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,903 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,906 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,906 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,909 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,909 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,912 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:14:27,912 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,871 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_group_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,874 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_group_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,876 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_licence_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,877 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_licence_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,879 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_organization_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,880 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_organization_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,882 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_role_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,883 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_role_pk_id_seq' in the database.
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,885 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:212 ] Unsuccessful: create sequence sec.t_user_pk_id_seq
[org.hibernate.tool.hbm2ddl.SchemaUpdate # ERROR # 02.01.2014 17:17:48,886 # main # SchemaUpdate.java # org.hibernate.tool.hbm2ddl.SchemaUpdate:execute:213 ] There is already an object named 'sec.t_user_pk_id_seq' in the database.
